baseURL: https://blog.harshkapadia.me
languageCode: en-us
title: Harsh Kapadia's Blog
theme: PaperMod
copyright: "&copy; 2021 [Harsh Kapadia](https://harshkapadia.me) |"
permalinks:
    posts: /:year/:filename
enableEmoji: true

enableRobotsTXT: true

minify:
    minifyOutput: true

params:
    env: production
    title: Harsh Kapadia's Blog
    description: Harsh Kapadia's Blog
    keywords: ["Harsh Kapadia", "Blog"]
    author: ["Harsh Kapadia"]
    images: "og-img.png"
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    assets:
        favicon: "favicon.ico"

    homeInfoParams:
        Title: "Hey, I'm Harsh."
        Content: |
            A [Web Developer](https://dev.harshkapadia.me), a [Speaker](https://talks.harshkapadia.me) and the Organiser at [Our Tech Community](https://ourtech.community).

            Apart from this blog, I've written about [Computer Networking](https://networking.harshkapadia.me) and [Git](https://git.harshkapadia.me).

    socialIcons:
        - name: Web Site
          url: "https://harshkapadia.me"
        - name: Twitter
          url: "https://twitter.com/harshgkapadia"
        - name: GitHub
          url: "https://github.com/HarshKapadia2"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/harshgkapadia"
        - name: email
          url: "mailto:contact@harshkapadia.me"

    cover:
        hiddenInList: true

menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags
          weight: 10
        - identifier: harshkapadia
          name: harshkapadia.me
          url: "https://harshkapadia.me"
          weight: 20
