baseURL: https://blog.harshkapadia.me
languageCode: en-us
title: Harsh Kapadia's Blog
theme: PaperMod
copyright: "[Harsh Kapadia](https://harshkapadia.me)"
permalinks:
    posts: /:year/:contentbasename
enableEmoji: true
enableRobotsTXT: true
minify:
    minifyOutput: true
params:
    env: production
    title: Harsh Kapadia's Blog
    description: Harsh Kapadia's Blog
    keywords: ["Harsh Kapadia", "Blog"]
    author: ["Harsh Kapadia"]
    images: ["og-img.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false
    assets:
        favicon: "favicon.ico"
    homeInfoParams:
        Title: "Hey, I'm Harsh."
        Content: |
            You can learn more about me at [harshkapadia.me](https://harshkapadia.me).
    socialIcons:
        - name: All links
          url: "https://links.harshkapadia.me"
        - name: email
          url: "mailto:contact@harshkapadia.me"
    cover:
        hiddenInList: false
menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags
          weight: 10
        - identifier: harshkapadia
          name: harshkapadia.me
          url: "https://harshkapadia.me"
          weight: 20
